Guión y actualización de Historias de Usuario.
ricardo-andre-pool-cen/Equipo-0_LIS pull request #104
Opened 2024-10-25 00:53 UTC by LuisGilDzib

Realicé una propuesta para el guion de la presentación y actualicé las historias de usuario que se acordaron.
Nota: perdón, no me di cuenta y actualicé la historias de usuario en el cuerpo del proyecto y no en  mi rama, no me di cuenta que estaba en el cuerpo del proyecto, pero solo lo edite en el apartado de español, el de inglés en el cuerpo del proyecto sigue intacto.

2024-10-25 15:45 UTC, ricardo-andre-pool-cen commented on ESPANOL/Act#6 Presentación.md
## Definición de Terminado:
### Documentación
- [ ] Es implementada en el Periodo_2, en el documento "Act#6_Presentacion".
- [ ] El contenido es traducido al ingles en un documento aparte.
- [ ] El documento en ingles se implementa en el Periodo_2, en el documento "Act#6_Presentacion".
- [ ] Se aplica formato markdown correctamente.
- [ ]  La redacción es comprensible y tiene buena ortografía.
### Tarea
- [ ] Se toman las 4 preguntas de base para redactar el boceto del guion.
- [ ] La redacción de las partes del video es de mediana exactitud o mas.

2024-10-25 15:50 UTC, ricardo-andre-pool-cen requested changes
Esta bien, sin embargo, te olvidas de que la importacion de contenidos debe ser hacia la rama "Cuerpo_del_proyecto", no hacia la mia, deberias cerrar esta solicitud y crear otra hacia el cuerpo.

2024-10-25 16:30 UTC, LuisGilDzib commented
ok

2024-10-28 17:18 UTC, ricardo-andre-pool-cen approved these changes
## Definición de Terminado:
### Documentación
- [ ] Es implementada en el Periodo_2, en el documento "Act#6_Presentacion".
- [X] El contenido es traducido al ingles en un documento aparte.
- [ ] El documento en ingles se implementa en el Periodo_2, en el documento "Act#6_Presentacion".
- [X] Se aplica formato markdown correctamente.
- [X]  La redacción es comprensible y tiene buena ortografía.
### Tarea
- [X] Se toman las 4 preguntas de base para redactar el boceto del guion.
- [X] La redacción de las partes del video es de mediana exactitud o mas.

Se tomará la actividad, el orden de la documentación es incorrecta, pero todo eso se va a cambiar.

2024-10-28 17:19 UTC, merged