revisión del apartado de nuevos requisitos
ricardo-andre-pool-cen/Equipo-0_LIS pull request #42
Opened 2024-09-26 21:50 UTC by LuisGilDzib

2024-09-26 21:52 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio permitirá guardar información de manera ordenada.
¿que tipo de informacion? ¿que es "ordenado"? ambiguedad

2024-09-26 21:53 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio puede ser de caracter público o privado.
puedes especificar un poquito mas, solo para mejor redaccion

2024-09-26 21:53 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio permitirá guardar información de manera ordenada.
Toda palabra existente es ambiguedad

2024-09-26 21:53 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio deberá contener al menos un miembro/ usuario.
Ya existe ese requisito y no se describe literalmente asi

2024-09-26 21:53 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio acepta una cantidad limitada de personas en este.
¿cuantas?

2024-09-26 21:53 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• La creación del repositorio implica la creación de una cuenta de usuario.
¿primero creas el repositorio y luego una cuenta?

2024-09-26 21:54 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El lider del repsoitorio puede asignar roles.
Ya existe

2024-09-26 21:54 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio permitirá guardar información de manera ordenada.
no existe palabra en el universo bien definida.

2024-09-26 21:54 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio permitirá guardar información de manera ordenada.
pero de todas maneras se puede cambiar el tipo de frase

2024-09-26 21:56 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio permitirá guardar información de manera ordenada.
la puedo cambiar de ordenada a " de una correcta arquitectura", que es un poco mas claro

2024-09-26 21:56 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio permitirá guardar información de manera ordenada.
Pero si existe el bien y el mal, y mi conciencia única realidad dice que esta mal.

2024-09-26 21:57 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio permitirá guardar información de manera ordenada.
> la puedo cambiar de ordenada a " de una correcta arquitectura", que es un poco mas claro

No, sigues siendo muy general, se tiene que redactar cada detallito de la función

2024-09-26 21:58 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio permitirá guardar información de manera ordenada.
aunque el apartado de "ordenada" se refiere a que lo que aparezca en pantalla no" choque", que "se vea bien la plataforma" asi que ordenada o arquitectura son palabras que definen bien lo necesario a expresar.

2024-09-26 22:01 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio puede ser de caracter público o privado.
pero la redacción usada es formal :(

2024-09-26 22:02 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio acepta una cantidad limitada de personas en este.
no lo puedes definir porque no sabes como opera el sistema, podrias decir 5 personas pero a la hora no será así, o puede tener cambios, no será general.

2024-09-26 22:02 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio permitirá guardar información de manera ordenada.
> aunque el apartado de "ordenada" se refiere a que lo que aparezca en pantalla no" choque", que "se vea bien la plataforma" asi que ordenada o arquitectura son palabras que definen bien lo necesario a expresar.

No, si te metes con la arquitectura te metes con lo no funcional o incluso con el prototipo funcional, no nos interesa especificar eso ahora

2024-09-26 22:03 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio acepta una cantidad limitada de personas en este.
asi que es mejor dejarlo a número limitado para que los de diseño se encargué de cuantos soporta el repo

2024-09-26 22:04 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio permitirá guardar información de manera ordenada.
> > aunque el apartado de "ordenada" se refiere a que lo que aparezca en pantalla no" choque", que "se vea bien la plataforma" asi que ordenada o arquitectura son palabras que definen bien lo necesario a expresar.
> 
> No, si te metes con la arquitectura te metes con lo no funcional o incluso con el prototipo funcional, no nos interesa especificar eso ahora

Incluso tendrias que especificar  cuantos pasos y tiempo requieres para llegar al contenido que declaras "ordenado"

2024-09-26 22:06 UTC, LuisGilDzib commented on Requisitos funcionales
> +• La creación del repositorio implica la creación de una cuenta de usuario.
la redacción es correcta, te dice que la creación del repositorio implica ( no se puede hacer a menos que) la creación de una cuenta de usuario. es decir para crear un repo necesitas tener una cuenta primero, pero esa no es una redacción formal, clara y sintetizada, es informal.

2024-09-26 22:08 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio puede ser de caracter público o privado.
> pero la redacción usada es formal :(

¿que no podria ser: "El repositorio puede ser establecido como publico: que permitirá la visualización a cualquier usuario; o privado: que limitara la visualización a los integrantes."?

2024-09-26 22:10 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio acepta una cantidad limitada de personas en este.
> no lo puedes definir porque no sabes como opera el sistema, podrias decir 5 personas pero a la hora no será así, o puede tener cambios, no será general.

entiendo el punto, pero si se puede especificar porque explica como funciona el programa, el tamaño de los equipos en este caso, los recursos tecnológicos que consuma es otra cosa, y es requisito no funcional.

2024-09-26 22:10 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El lider del repsoitorio puede asignar roles.
pero el tuyo solo enfoca al lider y no contiene a los miembros, u colaboradores "el repositorio le asigna un rol predeterminado de lider al creador de este" describiste pero solo dice que puede asignar el rol de lider pero no otros como el de miembro u colaborador, para hacerlo general se dice asignar roles, sea cual sea esos roles.

2024-09-26 22:11 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• La creación del repositorio implica la creación de una cuenta de usuario.
> la redacción es correcta, te dice que la creación del repositorio implica ( no se puede hacer a menos que) la creación de una cuenta de usuario. es decir para crear un repo necesitas tener una cuenta primero, pero esa no es una redacción formal, clara y sintetizada, es informal.

Pero omites pasos e incluso reduces requisitos, esa propiedad ya fue escrita de manera coherente: "el usuario debe crear una fuenta", y posteriormente se redacta: "el usuario puede crear repositorios".

2024-09-26 22:11 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio deberá contener al menos un miembro/ usuario.
eso acabo de leer en los requisitos de tu branch.

2024-09-26 22:13 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio puede ser de caracter público o privado.
no existe otro carácter , la información o es publica o privada pero no existe otro tipo de información, no hay un tercero.

2024-09-26 22:13 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio deberá contener al menos un miembro/ usuario.
> eso acabo de leer en los requisitos de tu branch.

pero si ya te lo habia dicho en la mensajeria verde

2024-09-26 22:16 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio permitirá guardar información de manera ordenada.
> Pero si existe el bien y el mal, y mi conciencia única realidad dice que esta mal.

define bien y mal, en cada ambito del mundo cambia su significo o en puntos de vista lo que te puede parecer bien puede ser malo para otras personas, asi que no todo en el mundo puede ser bueno o malo para diferentes personas.

2024-09-26 22:18 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El lider del repsoitorio puede asignar roles.
> pero el tuyo solo enfoca al lider y no contiene a los miembros, u colaboradores "el repositorio le asigna un rol predeterminado de lider al creador de este" describiste pero solo dice que puede asignar el rol de lider pero no otros como el de miembro u colaborador, para hacerlo general se dice asignar roles, sea cual sea esos roles.

me refiero a una funcion clave del repositorio es ese rol predeterminado, y posteriormente redacte: "los roles pueden ser modificados", incitando a que el usuario cree sus propios roles con el nombre que quiera, posteriormente redacte: "Los roles con el permiso otorgado pueden añadir tareas en un repositorio."; haciendo enfasis en que los roles con los permisos correspondientes podran modificar todas las cosas en el repositorio. Podemos añadir un requisito mas especifico, pero quiero que comprendas porque "ya existe".

2024-09-26 22:20 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio permitirá guardar información de manera ordenada.
> > Pero si existe el bien y el mal, y mi conciencia única realidad dice que esta mal.
> 
> define bien y mal, en cada ambito del mundo cambia su significo o en puntos de vista lo que te puede parecer bien puede ser malo para otras personas, asi que no todo en el mundo puede ser bueno o malo para diferentes personas.

esta bien cuando lo especificas mas en un requisito de prototipo funcional, pero este no es funcional, lo corriges.

2024-09-26 22:22 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio puede ser de caracter público o privado.
> no existe otro carácter , la información o es publica o privada pero no existe otro tipo de información, no hay un tercero.

no se a que te refieres pero ahi solo añadi mas especifidad para declarar que es el caracter "publico" o "privado", no puedes suponer que asi se entiende para cualquier programa, no puedes suponer nada leyendo requisitos, como quiera, ese nuevo si pasa como tuyo.

2024-09-26 22:22 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio permitirá guardar información de manera ordenada.
ok

2024-09-26 22:23 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio puede ser de caracter público o privado.
ok

2024-09-26 22:25 UTC, LuisGilDzib commented on Requisitos funcionales
> +• La creación del repositorio implica la creación de una cuenta de usuario.
ok

2024-09-26 22:28 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El lider del repsoitorio puede asignar roles.
ok

2024-09-26 22:30 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio acepta una cantidad limitada de personas en este.
ok

2024-09-26 23:47 UTC, LuisGilDzib commented
Hola rodrigo, continuamos usando este pull request o creo otro nuevo?

2024-09-27 00:36 UTC, ricardo-andre-pool-cen requested changes
Revisiones aplicadas

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• Los usuarios registrados en el pseudorepositorio pueden ser los miembros de un repositorio.
¿no es muy obvio?,  "seudo-repositorio" es el nombre del proyecto o un apodo, dentro de nuestro programa solo es "repositorio", puedes escribir: "Los usuarios pueden solicitar su integración para formar parte de un repositorio"

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• Los miembros del repositorio tendrán una jerarquia, de colaborador a lider del repositorio.
pero ¿Quién define eso? ¿la maquina o el usuario?, la maquina solo ha decidido el rol de líder, pero se hace énfasis en que los roles son "modificables" porque se supone que el usuario decida como ordena su jerarquía mediante los distintos permisos, puedes poner: "El momento de crearse, el repositorio crea una jerarquía predeterminada con roles y permisos definidos básicos para los integrantes, totalmente modificable"

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• Los miembros del repositorio podran escribir y editar la información contenida en el repositorio.
¿Qué tipo de información? puedes explicar eso en mas requisitos. Ejemplo: "Los usuarios pueden modificar el nombre y descripción de su pizarrón personal", "Los usuarios con los permisos otorgados por un rol asignado pueden modificar otros roles", "Los usuarios con los permisos otorgados por un rol asignado pueden modificar el contenido de otros pizarrones personales: añadir, editar, mover o eliminar."

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• Los miembros del repositorio podrán elmiminar información del repositorio en cualquier momento.
¿Todos los miembros? lo mismo que el comentario anterior, define quienes y que informacion.

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• Los miembros del repositorio tendrán opción de mensajería que permitirá escribir comentarios en el repositorio.
¿una mensajería general dentro del repositorio?, falta especificar un poco mas, puede ser: "El repositorio contiene un chat general para todos los integrantes."

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• Los miembros del repositorio tendrán acceso restringido a las funciones del repositorio según su jerarquía.
¿Qué son las "funciones del repositorio"? Puedes definirlo como: "Solo los usuarios con el permiso otorgado por un rol asignado podrán cerrar tareas", "Solo los usuarios con el permiso otorgado por un rol asignado podrán expulsar a otros integrantes".

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• Las ramas en un repositorio son una fuente de almacenamiento de información para los miembros del repositorio.
Ya lo platicamos, y debes seguir escribiendo cada requisito como una posibilidad o afirmación y no como definición. Corrección: "El repositorio puede contener "ramas" o pizarrones personales para cada uno de los integrantes."

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• Las ramas pueden ser específicas para cada mienbro del repositorio o pueden ser generales para todos los miembros.
Bien

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• Las peticiones de revisión es una función que puede hacer el miembro para pedir la revisión de la información contenida en su rama por parte de los miembros de otras ramas dentro del repositorio.
Puede ser: "Los usuarios pueden realizar "solicitudes de revisión" para convocar a mas integrantes a revisar el contenido dentro de su pizarrón personal."

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio puede ser de caracter público: la información dentro de este será visible para cualquier persona.
Bien

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio puede ser de caracter privado: la información dentro del repositorio sólo será visible para los miembros.
Bien

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El lider del repositorio puede elegir si el repositorio es de caracter público o privado en cualquier momento.
Bien, pero igual cualquier persona con el permiso otorgado por un rol asignado podría hacerlo.

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio acepta una cantidad de 10 usuario como máximo en un repositorio, siendo el mínimo de 1 usuario.
No es necesario especificar el mínimo: ya se explico cuando el ultimo usuario no puede salirse del repositorio sino debe borrarlo.

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El lider de equipo tendrá la opción de agregar asignaciones a los miembros del repositorio.
Tambien cualquier persona con el permiso otorgado por un rol asignado podría hacerlo.

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• Las asignaciones pueden ser para un grupo de miembros o individuales.
Bien

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• Las asignaciones deberán contener nombre y descripción para informar corectamente a los miembros sobre lo que requiere la asignación otorgada.
Recuerda que solo se explica como trabaja el sistema, no como debe operar el usuario. Corrección: "Las asignaciones pueden tener nombre, descripción, archivos adjuntos, fecha de apertura y fecha de entrega.", también puedes especificar que acciones puede hacer un usuario con una actividad asignada

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• Los miembros de la asignación pueden adjuntar archivos en la asignación.
Bien, poquito mas de redaccion

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• Las asignaciones tienen fecha de inicio y cierre.
Bien

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• Las asignaciones guardan la fecha de entrega de cada miembro de la asignación.
Bien

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• Las asignaciones clasifican las fechas de entrega en: entregado (se entregó entre el tiempo de incio y cierre) y entregado con retraso (se entregó despúes de la fecha de cierre).
Puede ser distinto, es decir, cuando la asignación se declara entregada, se crea un comentario: "Temprano", "Justo a tiempo", "Atrasado", "Irresponsabilidad"

2024-09-27 00:36 UTC, ricardo-andre-pool-cen commented on Requisitos funcionales
> +• El repositorio contiene una línea del tiempo donde se muestran la fechas de inicio, cierre y entrega de las asignaciones.
No esta bien redactado, la linea de tiempo es para todo el repositorio, puede ser: "Las fechas de inicio, cierre y entrega de las asignaciones son desplegadas en la linea de tiempo del repositorio"

2024-09-27 00:43 UTC, LuisGilDzib commented on Requisitos funcionales
> +• Los usuarios registrados en el pseudorepositorio pueden ser los miembros de un repositorio.
ok

2024-09-27 00:44 UTC, LuisGilDzib commented on Requisitos funcionales
> +• Los miembros del repositorio tendrán una jerarquia, de colaborador a lider del repositorio.
ok

2024-09-27 00:44 UTC, LuisGilDzib commented on Requisitos funcionales
> +• Los miembros del repositorio podran escribir y editar la información contenida en el repositorio.
ok

2024-09-27 00:44 UTC, LuisGilDzib commented on Requisitos funcionales
> +• Los miembros del repositorio podrán elmiminar información del repositorio en cualquier momento.
ok

2024-09-27 00:45 UTC, LuisGilDzib commented on Requisitos funcionales
> +• Los miembros del repositorio tendrán opción de mensajería que permitirá escribir comentarios en el repositorio.
ok

2024-09-27 00:45 UTC, LuisGilDzib commented on Requisitos funcionales
> +• Los miembros de la asignación pueden adjuntar archivos en la asignación.
ok

2024-09-27 00:49 UTC, LuisGilDzib commented on Requisitos funcionales
> +• Las asignaciones clasifican las fechas de entrega en: entregado (se entregó entre el tiempo de incio y cierre) y entregado con retraso (se entregó despúes de la fecha de cierre).
pero al hacer eso tendrías que definir en que lapso de tiempo el sistema mandará esos mensaje,  por eso el apartado de entregado esta definido en el tiempo de inicio a cierre y el de retraso después del tiempo de cierre, si gustas eso de temprano, irresponsabilidad me podrías proporcionar el lapso de tiempo, es que no tengo idea de como dividir el tiempo si solo tengo la info de inicio y cierre de la asignación.

2024-09-27 00:50 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio contiene una línea del tiempo donde se muestran la fechas de inicio, cierre y entrega de las asignaciones.
ok

2024-09-27 01:12 UTC, LuisGilDzib commented on Requisitos funcionales
> +• Las peticiones de revisión es una función que puede hacer el miembro para pedir la revisión de la información contenida en su rama por parte de los miembros de otras ramas dentro del repositorio.
ok

2024-09-27 01:12 UTC, LuisGilDzib commented on Requisitos funcionales
> +• Las ramas en un repositorio son una fuente de almacenamiento de información para los miembros del repositorio.
ok

2024-09-27 01:14 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El lider del repositorio puede elegir si el repositorio es de caracter público o privado en cualquier momento.
ok

2024-09-27 01:14 UTC, LuisGilDzib commented on Requisitos funcionales
> +• El repositorio acepta una cantidad de 10 usuario como máximo en un repositorio, siendo el mínimo de 1 usuario.
ok

2024-09-27 01:20 UTC, closed without merging