Nuevos requisitos funcionales
ricardo-andre-pool-cen/Equipo-0_LIS pull request #43
Opened 2024-09-27 00:48 UTC by Car1los333

Espero que sean suficientes los requerimientos funcionales

2024-09-27 00:54 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Los usuario podran crear su usuario y contraseña para acceder a su cuEnta Personal.
Ya existe, falta mejorar redacción profesional.

2024-09-27 00:54 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Los usuario podran recuperar su contraseña mediante un proceso seguro.
Puede ser

2024-09-27 00:55 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El pseurepositorio cuenta con una barra de busqueda para buscar el archivo o repositorio que se requiera.
Recuerda que dentro del programa es solo "repositorio", "seudo-repositorio" es el nombre del producto y proyecto, es buena idea.

2024-09-27 00:55 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Los usuarios podran Crear, Eliminar y actualizar cualquier Repositorio.
Hay mucha ambigüedad ahí, y ya se redactaron requisitos de ese estilo, revisa la retroalimentación con Luis

2024-09-27 00:57 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Los usuarios podran invitar a otros usuarios a colaborar con el proyecto y gestionar los permisos de acceso.
La funcion es buena, la redaccion no, puede ser asi: "Los integrantes con el permiso otorgado mediante roles asignados pueden invitar a otros usuarios a formar parte del repositorio"

2024-09-27 00:58 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Los usuarios podran acceder a un historial de cambios y revertir algun proceso que se requiera.
Recuerda que son solo "Los integrantes con el permiso otorgado mediante roles asignados...", podrías especificar en que áreas de trabajo aplica esa función, Ejemplo: "Los integrantes con el permiso otorgado mediante roles asignados podrán revertir cambios aplicados a la rama principal del repositorio", de ahí creas mas requisitos.

2024-09-27 00:59 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El pseudorepositorio cuanta con una interfaz amigable.
Eso es de diseño y ambiguo.

2024-09-27 01:00 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El pseudorepositorio debe de mantener los datos seguros y eficientes.
Eso es ambiguo también, hay un requisito para eso, es el siguiente: "El repositorio tiene dos respaldos de la información y configuraciones agregadas por los integrantes"

2024-09-27 01:02 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El pseudorepositoro contara con un sistema de notificaciones para avisar a los usuarios, estos podran  ser enviados por Gmail o SMS.
No puedes definir herramientas, solo el concepto, puede ser: "Un repositorio puede enviar notificaciones a sus integrantes"., y de ahí descomponer mas requisitos por función, ejemplo: "El repositorio enviará una notificación a sus integrantes cuando se revierta un cambio en la rama principal"

2024-09-27 01:02 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario podra exportar diferentes formartos (PDF. EXCEL, ETC).
No puedes definir herramientas

2024-09-27 01:02 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario podra cambiar su foto de perfil y colocar alguna descripcion sobre él
Bien, puedes extraer mas requisitos de eso

2024-09-27 01:02 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario podra descargar archivos del repositorio
Bien

2024-09-27 01:03 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario podra colocar comentarios en los repositorios
Debes especificar en que parte de las funciones y extraer mas requisitos, Ejemplo: "Los integrantes podrán agregar comentarios al contenido agregado por un integrante dentro de su pizarrón personal"

2024-09-27 01:03 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario podra  recibir notificaciones
Añadiste lo mismo

2024-09-27 01:03 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Los usuarios podran etiquetar los archivos para mayor facilidad de busquedad
Puede ser

2024-09-27 01:04 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Los usuarios podran clasidicar los archivcos en diferentes categorias
¿No es lo mismo que las etiquetas?

2024-09-27 01:04 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Los usarios podran proporcionar permisos de acceso
Ya esta escrito el requisito como "permisos de rol"

2024-09-27 01:04 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El sistema podra conectarse con algun servicio externo como Google Drive o Dropbox
No puedes usar herramientas

2024-09-27 01:04 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El sistema podra registrar la actividad de cada usuario
Ya esta descrito

2024-09-27 01:04 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El sistema soportara un lenguaje Bilingue
Explica mejor ese, ¿dos idiomas?

2024-09-27 01:05 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Los usuarios podran visualizar los archivos antes de descargar
No es necesario, un integrante puede saber que archivo va a descargar antes de efectuar esa accion

2024-09-27 01:05 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El sistema contara con mecanismos de respaldo y recuperacion de datos
Ya esta descrito

2024-09-27 01:06 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El sistema debe de monitoriar el sistema y enviar una alerta en caso de algun problema
¿Que problemas? no uses ambiguedad, puedes descomponer mas requisitos

2024-09-27 01:06 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El sistema tendra como herramienta Microsoft teams
No añadas herramientas

2024-09-27 01:06 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El sistema podra soportar la carga y descarga de archivos grandes
Eso seria parte de la construccion, son herramientas, no pienses en eso

2024-09-27 01:07 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Los usuarios podran colaborar en tiempo real en los documentos
No estamos seguros sobre documentos pero si sobre los pizarrones personales, corrección: "Los usuarios pueden colaborar en tiempo real en los pizarrones personales"

2024-09-27 01:08 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Podra gestionar miltiples proyectos
Eso no es exacto, ¿te refieres a la cantidad de repositorios?, un usuario solo puede estar integrado o ser dueño de 10

2024-09-27 01:08 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El sistema podra soportar archivos como Videos y audios
Aun no se describe eso, son herramientas

2024-09-27 01:09 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Los administradores podran gestionar permisos y usuarios
Ya esta descrito

2024-09-27 01:09 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El sistema podra soportar dos formas de autenticacion de dos factores para una mayor seguridad.
Puede ser

2024-09-27 01:09 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +Nuestro pseurepositorio debera poder soportar 5000 solicitudes por segundo.
Eso no va

2024-09-27 01:09 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +Podra soportar un monumento de carga de trabajo
Explica mejor el requisito

2024-09-27 01:10 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +Los datos deneran estar cifrados o que cuenten con alguna seguridad
Debes explicar mejor el requisito, ¿se pueden proteger los documentos?

2024-09-27 01:10 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +El pseurepositorio debera ser compatible con cualquier navegador Web
Nada de herramientas

2024-09-27 01:10 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +Debera de funcionar en cualquier sistema operativo que se requiere
Que nada de herramientas

2024-09-27 01:10 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +Debera de contar con algun plan de recuperación por alguna falla.
Esta descrito, el repositorio tiene dos respaldos

2024-09-27 01:10 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +El tiempo de respuesta debe ser adecuado para su funcionamiento
Nada de herramientas ni calidad de hardware

2024-09-27 01:11 UTC, ricardo-andre-pool-cen commented on Carlos
> +EspadasrlosCa
puedes borrar este archivo

2024-09-27 01:11 UTC, ricardo-andre-pool-cen requested changes
Favor de leer los cambios

2024-09-27 01:45 UTC, Car1los333 commented
De parte de Perla te mando su parte.
https://www.canva.com/design/DAGRbqtMrHk/Vh50Q50F2LQB1jtpNk5CXQ/edit?utm_content=DAGRbqtMrHk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

2024-09-27 15:11 UTC, Car1los333 commented
https://www.canva.com/design/DAGRbqtMrHk/Vh50Q50F2LQB1jtpNk5CXQ/edit

2024-09-28 00:23 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario contara con un Unbording para configurar el perfil
No es necesario redactar este requisito si lo pondrás posteriormente abajo

2024-09-28 00:23 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario puede colocar sus debilidades
¿Por qué pondría eso?

2024-09-28 00:23 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario puede colocar los lugares donde haya trabajado.
No es necesario para este seudo-repositorio

2024-09-28 00:25 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario puede colocar su edad
puedes redactar mas completo el requisito, ejemplo: "El perfil de usuario tiene un apartado modificable para la edad del usuario"

2024-09-28 00:25 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario puede colocar su nivel de estudio alcanzado
No es necesario para el seudo-repositorio

2024-09-28 00:25 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario puede colocar los años de experiencia trajando
No va con nuestros usuarios

2024-09-28 00:25 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario puede colocar el lugar donde estudio
No es necesario para el seudo-repositorio

2024-09-28 00:26 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario puede colocar en que rama se destaca.
Explica mejor el requisito

2024-09-28 00:26 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario puede colocar sus SkinCare
¿Qué es eso?

2024-09-28 00:26 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario puede colocar los idiomas que habla.
No va con nuestros usuarios

2024-09-28 00:27 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El Onbording no se puede omitir
puedes redactar de manera mas profesional, ejemplo: "La guía de estilo "onboarding" proporcionada por el sistema no se puede omitir durante su ejecución."

2024-09-28 00:27 UTC, ricardo-andre-pool-cen commented on Trabajo de perla
> +https://www.canva.com/design/DAGRbqtMrHk/Vh50Q50F2LQB1jtpNk5CXQ/edit
Ya lo recibí de parte de ella

2024-09-28 00:28 UTC, ricardo-andre-pool-cen requested changes
Revisa los cambios y redacta de nuevo los requisitos

2024-09-28 21:51 UTC, ricardo-andre-pool-cen requested changes
No te corresponden hacer no funcionales, no haz hecho revisión de los funcionales.

2024-09-28 22:04 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El Seudo-Repositorio cuenta con una barra de busqueda para buscar el archivo o repositorio que se requiera.
Puede ser: "Los usuarios pueden encontrar cualquier archivo dentro de un repositorio mediante una opción de búsqueda"

2024-09-28 22:05 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Los Integrantes con el permiso ocupado mendiante roles asignados pueden invitar a otros usurios a formar parte del repositorio.
Errores ortográficos, es: "Los integrantes con el permiso otorgado mediante roles asignados pueden invitar a otros usaurios a formar parte del repositorio.", pero esta bien.

2024-09-28 22:06 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Los integrantes con el permiso ocupado mendiante roles asignados podran revertir cambios a las rama principal del repositorio
Revisa tu ortografía, es: "Los integrantes con el permiso otorgado mediante un rol asignado pueden revertir los cambios a las ramas del repositorio"

2024-09-28 22:08 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario con algun rol asigando puede  revertir el proceso de borrado de algun repositorio.
¿Que quieres decir?, ¿Se pueden recuperar repositorios borrados? ¿No eso era imposible? o ¿Te refieres al mismo requisito de arriba? Nadie debe suponer nada leyendo requisitos.

2024-09-28 22:10 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario con algun rol asignado puede modificar el titulo de un repositporio.
Ya esta escrito, puedes generalizar: "Los usuarios con el permiso otorgado mediante un rol asignado pueden modificar los datos básicos del repositorio" porque anteriormente se especifican cuales son

2024-09-28 22:10 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El Seudo-Repositorio debe de mantener los datos seguros y eficientes.
Eso es muy ambiguo y es no funcional

2024-09-28 22:10 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +EL repositorio envia una notificacion a sus integrantes de cualquier cambio en la rama principal
Bien

2024-09-28 22:12 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario puede activar la opción de notificaciones o silenciarlo.
ya existe ese requisito

2024-09-28 22:12 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario puede  exportar diferentes formartos (PDF. EXCEL, ETC).
¿Por qué volviste a poner herramientas que no van?

2024-09-28 22:13 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario puede colocar comentarios en los repositorios
Puede ser: "Los usuarios externos pueden colocar comentarios sobre otros repositorios de carácter publico."

2024-09-28 22:14 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Los usuarios pueden etiquetar los archivos para mayor facilidad de busquedad.
Puede ser

2024-09-28 22:14 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario puede adaptar el idioma del repositorio.(Ingles, Español).
Mas que nada, la interfaz del usuario es cambiable entre idiomas, puede ser: "El usuario puede modificar el idioma con el que lee el programa: ingles o español"

2024-09-28 22:16 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El seudo-Repositorio puede  registrar la actividad de cada usuario.
Eso es no funcional.

2024-09-28 22:19 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +Los usuarios pueden interactuar en tiempo real  en el pizzaron virtual.
No hay exactitud, ¿que pizarron?, no es necesario especificar que es en tiempo real, debe ser: "Los integrantes pueden modificar los datos de sus pizarrones personales"
Anteriormente debes redactar cuales son los datos modificables de los pizarrones personales.

2024-09-28 22:20 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario puede colocar una foto de perfil o Avatar
En realidad es: "El usuario puede cambiar la foto de su perfil"

2024-09-28 22:20 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
> +El usuario puede colocar sus Hobbies y Gustos
Puede ser "El usuario puede definir sus gustos personales en una sección dedicada dentro del Perfil"

2024-09-28 22:21 UTC, ricardo-andre-pool-cen commented on Carlos
> +EspadasrlosCa
No lo has borrado

2024-09-28 22:21 UTC, ricardo-andre-pool-cen commented on Trabajo de perla
Borra este documento tambien

2024-09-28 22:22 UTC, ricardo-andre-pool-cen requested changes
Ya casi los tienes, haz seguimiento de las indicaciones y acuérdate de las funciones del sistema que son necesarias de describir

2024-09-28 22:30 UTC, Car1los333 commented
Ok en eso estoy

2024-09-29 00:36 UTC, ricardo-andre-pool-cen commented
Reformado el criterio de actividad, esta practica les ayudó a tener una idea concreta del proyecto y a aprender a redactar requisitos.

2024-09-29 00:36 UTC, closed without merging