Requisitos no funcionales
ricardo-andre-pool-cen/Equipo-0_LIS pull request #51
Opened 2024-09-28 02:04 UTC by jaimeo13

2024-09-28 02:07 UTC, ricardo-andre-pool-cen commented on Act#1 Descripción del proyecto.
No corregiste este contenido.

2024-09-28 02:07 UTC, ricardo-andre-pool-cen commented on Act#3 Requisitos Funcionales
No se te fueron asignados requisitos funcionales

2024-09-28 02:09 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +RNF_000: El sistema descarga el repositorio de forma local
¿A que te refieres con eso?, ¿Cuál es el propósito de esa función?, te falta explicar mas.

2024-09-28 02:09 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +RNF_000: Los errores del programa se reparan en por lo menos ocho horas
te dije que no expliques herramientas

2024-09-28 02:09 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +RNF_000: El uso en la página web o programa tiene que tener una interfaz similar en cualquier dispositivo
Caso omiso de las indicaciones

2024-09-28 02:09 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +RNF_000: El usuario no puede tener más de dos fallas
¿A que te refieres con eso?

2024-09-28 02:10 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +RNF_000: Se puede volver a una versión anterior del repositorio
Eso seria un requisito funcional, no esta especificado y no se te fueron asignados funcionales

2024-09-28 02:10 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +RNF_000: No se puede tener más de una cuenta por correo
Caso omiso de las indicaciones: nada de herramientas

2024-09-28 02:11 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +RNF_000: En la eliminación de la cuenta no se recuperaran los repositorios que creo el usuario
Falta especificar mas: ¿Y si el repositorio aun tiene integrantes?, trabájalo.

2024-09-28 02:14 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +RNF_000: El uso de un corrector ortográfico de forma automática
Puede ser, pero necesito que lo redactes mejor, ¿en donde se implementara un corrector ortográfico?
(Trabajar)

2024-09-28 02:16 UTC, ricardo-andre-pool-cen requested changes
Sigues con muchas fallas, favor de seguir las instrucciones.

2024-09-28 02:48 UTC, jaimeo13 commented on Act#4 Requisitos no funcionales
> +RNF_000: Los errores del programa se reparan en por lo menos ocho horas
Es un requisito no funcional de mantenimiento

2024-09-28 02:48 UTC, jaimeo13 commented on Act#4 Requisitos no funcionales
> +RNF_000: El uso en la página web o programa tiene que tener una interfaz similar en cualquier dispositivo
Es un requisito no funcional de compatibilidad

2024-09-28 02:58 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +RNF_000: Los errores del programa se reparan en por lo menos ocho horas
> Es un requisito no funcional de mantenimiento

No tenemos programa, no puedes definir como se va a reparar, esta mal.

2024-09-28 02:58 UTC, ricardo-andre-pool-cen commented on Act#4 Requisitos no funcionales
> +RNF_000: El uso en la página web o programa tiene que tener una interfaz similar en cualquier dispositivo
> Es un requisito no funcional de compatibilidad

No debes explicar diseño, nadie dijo que seria pagina web, nada de herramientas, esta mal

2024-09-28 02:59 UTC, ricardo-andre-pool-cen commented on Act#1 Descripción del proyecto.
¿Por qué aun no borras este contenido?

2024-09-28 03:00 UTC, ricardo-andre-pool-cen requested changes
No arreglaste los errores, redacta otra vez los requisitos, que ya son pocos los que debes.

2024-09-29 00:37 UTC, ricardo-andre-pool-cen commented
Reformado el criterio de actividad, esta practica les ayudó a tener una idea concreta del proyecto y a aprender a redactar requisitos.

2024-09-29 00:37 UTC, closed without merging